# Generated by Django 3.2.2 on 2021-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210510_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='static/images/user.png', upload_to='static/images/profile'),
        ),
    ]
