# Generated by Django 3.2.2 on 2021-05-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210511_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.religion')),
            ],
        ),
    ]
