# Generated by Django 3.2.2 on 2021-05-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210511_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.caste'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.religion'),
        ),
    ]
