# Generated by Django 3.2.2 on 2021-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210514_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nakshatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='annual_income',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A +', 'A +'), ('B +', 'B +'), ('A -', 'A -'), ('B -', 'B -'), ('AB -', 'AB -'), ('AB +', 'AB +'), ('O +', 'O -'), ('O -', 'O -'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='body_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('Athletic', 'athletic'), ('Other', 'other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='complexion',
            field=models.CharField(choices=[('fair', 'Fair'), ('whiteatish', 'Whiteatish'), ('dark', 'Dark')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employed_in',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
