# Generated by Django 3.2.2 on 2021-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210516_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SprortType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='astronamy',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='diet',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('vegitarian', 'Vegiterian'), ('eggetarian', 'Eggetarian'), ('nonvegiterian', 'NonVegiterian')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='drinking',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('special functions', 'Special Functions only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gardening',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='music',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='smoking',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='residential_status',
            field=models.CharField(choices=[('own', 'Own'), ('rented', 'Rented'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
