# Generated by Django 3.2.2 on 2021-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210516_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dress',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dress_types',
            field=models.ManyToManyField(null=True, to='customer.DressType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='food_type',
            field=models.ManyToManyField(null=True, to='customer.FoodType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='foods',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longtitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='movie',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='movie_types',
            field=models.ManyToManyField(null=True, to='customer.MovieTypes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='music_types',
            field=models.ManyToManyField(null=True, to='customer.MusicType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reading',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reading_types',
            field=models.ManyToManyField(null=True, to='customer.ReadingType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sport_types',
            field=models.ManyToManyField(null=True, to='customer.SprortType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sports',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_of_birth',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
