# Generated by Django 3.2.2 on 2021-05-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210516_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dress_types',
            field=models.ManyToManyField(to='customer.DressType'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='food_type',
            field=models.ManyToManyField(to='customer.FoodType'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='movie_types',
            field=models.ManyToManyField(to='customer.MovieTypes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='music_types',
            field=models.ManyToManyField(to='customer.MusicType'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reading_types',
            field=models.ManyToManyField(to='customer.ReadingType'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sport_types',
            field=models.ManyToManyField(to='customer.SprortType'),
        ),
    ]
