# Generated by Django 3.2.2 on 2021-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20210516_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
