# Generated by Django 3.2.2 on 2021-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='college_location',
            new_name='college_location_pg',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='college_name',
            new_name='college_location_ug',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='course',
            new_name='college_name_pg',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='year_of_passout_college',
            new_name='year_of_passout_college_pg',
        ),
        migrations.AddField(
            model_name='customer',
            name='college_name_ug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='course_pg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='course_ug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='year_of_passout_college_ug',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
