# Generated by Django 3.2.2 on 2021-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20210518_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='country_livig_in',
            new_name='country_living_in',
        ),
        migrations.AlterField(
            model_name='customer',
            name='complexion',
            field=models.CharField(blank=True, choices=[('fair', 'Fair'), ('whiteatish', 'Whiteatish'), ('dark', 'Dark')], max_length=20, null=True),
        ),
    ]
