# Generated by Django 3.2.2 on 2021-05-18 15:38

import customer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210518_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gardening',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
    ]
