# Generated by Django 3.2.2 on 2021-05-18 15:40

import customer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_customer_gardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dress',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='foods',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='movie',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='music',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reading',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sports',
            field=models.PositiveIntegerField(null=True, validators=[customer.validators.validate_num]),
        ),
    ]
